// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission04.Models;

namespace Mission04.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission04.Models.Category", b =>
                {
                    b.Property<int>("categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryname")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryid");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            categoryid = 1,
                            categoryname = "Action/Adventure"
                        },
                        new
                        {
                            categoryid = 2,
                            categoryname = "Comedy"
                        },
                        new
                        {
                            categoryid = 3,
                            categoryname = "Drama"
                        },
                        new
                        {
                            categoryid = 4,
                            categoryname = "Family"
                        },
                        new
                        {
                            categoryid = 5,
                            categoryname = "Horror/Suspense"
                        },
                        new
                        {
                            categoryid = 6,
                            categoryname = "Miscellaneous"
                        },
                        new
                        {
                            categoryid = 7,
                            categoryname = "Television"
                        },
                        new
                        {
                            categoryid = 8,
                            categoryname = "VHS"
                        });
                });

            modelBuilder.Entity("Mission04.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentto")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.HasIndex("Categoryid");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Categoryid = 1,
                            director = "Kevin Reynolds",
                            edited = false,
                            lentto = "",
                            notes = "One of the best movies ever made",
                            rating = "PG-13",
                            title = "The Count of Monte Cristo",
                            year = 2002
                        },
                        new
                        {
                            MovieId = 2,
                            Categoryid = 1,
                            director = "Michael Curtis",
                            edited = false,
                            lentto = "",
                            notes = "One of the best movies ever made",
                            rating = "PG",
                            title = "The Adventure of Robin Hood",
                            year = 1938
                        },
                        new
                        {
                            MovieId = 3,
                            Categoryid = 1,
                            director = "Christopher Nolan",
                            edited = false,
                            lentto = "",
                            notes = "One of the best movies ever made",
                            rating = "PG-13",
                            title = "Inception",
                            year = 2010
                        });
                });

            modelBuilder.Entity("Mission04.Models.MovieResponse", b =>
                {
                    b.HasOne("Mission04.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Categoryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
